### ISSUE TITLE
Version 4.4.0 Crash on 1.20

### ISSUE THREAD

**Issue by upcomingshoes** [d4rkm0nkey/HorseStatsVanilla#39]
Commonly encounter a crash on 1.20. It occurs when sneaking and right-clicking an untamed horse to view the stats. It does not occur with every horse, but is very common.

Crash log:

Time: 2023-06-24 00:15:32
Description: Rendering screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (monkey.lumpy.horse.stats.vanilla.gui.ToolTipGui) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1316)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:1339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.class_757.handler$zjb000$fabric-screen-api-v1$onBeforeRenderScreen(class_757.java:2138)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1316)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:1339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.class_757.handler$zjb000$fabric-screen-api-v1$onBeforeRenderScreen(class_757.java:2138)

-- Screen render details --
Details:
	Screen name: monkey.lumpy.horse.stats.vanilla.gui.ToolTipGui
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['upcomingshoes'/1136, l='ClientLevel', x=-44.66, y=63.00, z=-347.45]]
	Chunk stats: 4096, 1529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,68,-208), Section: (at 0,4,0 in -1,4,-13; chunk contains blocks -16,-64,-208 to -1,319,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 4911 game time, 4911 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by halsangar** [comment]
Its happening with me too when shift+right clicking on the horse. It looks like when checking via inventory its stable

**Comment by MemeKueen2** [comment]
the current most recently uploaded file is labeled 4.3.0
I think the previous version was accidentally uploaded instead of 4.4.0 hence the crashes because of incompatibility. for me, it would crash upon loading the world, no chance to even look at a horse.
