### ISSUE TITLE
[1.20.1] Shift+Click a Baby Horse makes the game crash

### ISSUE THREAD

**Issue by rezelyn** [d4rkm0nkey/HorseStatsVanilla#40]
**Game version:** 1.20.1
**Mod version:** [4.4.0](https://modrinth.com/mod/horsestatsvanilla/version/4.4.0)

If you try to `Shift+Click` a Baby Horse, it will open a litlle GUI with his stats and make the game crash after.

## Crash report:
```
java.lang.NullPointerException: Cannot read field "field_1687" because "this.field_22787" is null
	at net.minecraft.class_437.method_25420(class_437.java:331)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.paint(CottonClientScreen.java:127)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.method_25394(CottonClientScreen.java:148)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.method_25420(class_437.java:331)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.paint(CottonClientScreen.java:127)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.method_25394(CottonClientScreen.java:148)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: monkey.lumpy.horse.stats.vanilla.gui.ToolTipGui
	Mouse location: Scaled: (480, 270). Absolute: (961.000000, 540.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```
**API:** [Quilt](https://quiltmc.org/en/)
**API version:** 0.19.1

**Comment by rezelyn** [comment]
**Update:** It also does if you `Shift-Click` a non-tamed Horse/Donkey/Mule *(also for baby ones so)*
