### ISSUE TITLE
1.20.1 crash when ctrl-right clicking (sometimes only)

### ISSUE THREAD

**Issue by basocjk** [d4rkm0nkey/HorseStatsVanilla#47]
crash report: 

`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-01-27 13:27:19
Description: Rendering screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (monkey.lumpy.horse.stats.vanilla.gui.ToolTipGui) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialized(Screen.java:1816)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeRenderEvent(Screen.java:1839)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.client.render.GameRenderer.handler$bhc000$fabric-screen-api-v1$onBeforeRenderScreen(GameRenderer.java:4638)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialized(Screen.java:1816)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeRenderEvent(Screen.java:1839)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.client.render.GameRenderer.handler$bhc000$fabric-screen-api-v1$onBeforeRenderScreen(GameRenderer.java:4638)

-- Screen render details --
Details:
	Screen name: monkey.lumpy.horse.stats.vanilla.gui.ToolTipGui
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['kollide'/182, l='ClientLevel', x=967.19, y=65.00, z=131.75]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,74,94), Section: (at 0,10,14 in -3,4,5; chunk contains blocks -48,-64,80 to -33,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1438254 game time, 2118037 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:458)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/VanillaTweaks_r539416.zip, minecraft:supporteatinganimation, continuity:glass_pane_culling_fix, fabric, continuity:default

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2009704432 bytes (1916 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x591b
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2125
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20363.96
	Virtual memory used (MB): 15025.50
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 215.62
	JVM Flags: 9 total; -XX: UseG1GC -Xmx4G -Xms4G -XX: UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		betterchunkloading: Better chunk loading mod 1.20.1-2.6
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterf3: BetterF3 7.0.2
			cloth-config: Cloth Config v11 11.1.106
				cloth-basic-math: cloth-basic-math 0.6.1
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterfpsdist: Better FPS distance Mod 1.20.1-4.0
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bookshelf: Bookshelf 20.1.8
		c2me: Concurrent Chunk Management Engine 0.2.0 alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0 alpha.11.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0 alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0 alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0 alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0 alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0 alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0 alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0 alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0 alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0 alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0 alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0 alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0 alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0 alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0 alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0 alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0 alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0 alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0 alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0 alpha.11.0
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		chunky: Chunky 1.3.92
		continuity: Continuity 3.0.0-beta.4 1.20.1
		controllable: Controllable 0.20.2
			io_github_libsdl4j_libsdl4j: libsdl4j 2.26.4-1.2
		creeperoverhaul: Creeper Overhaul 3.0.1
			resourcefullib: Resourceful Lib 2.0.6
				com_teamresourceful_yabn: yabn 1.0.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.6
		cull-less-leaves: Cull Less Leaves 1.3.0
		cupboard: cupboard 1.20.1-2.2
		dashloader: DashLoader 5.0.0-beta.2 1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dynamic_fps: Dynamic FPS 3.3.3
		eatinganimationid: Eating Animation 1.20 1.9.5
		enhancedblockentities: Enhanced Block Entities 0.9 1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0 1.20
		fabric-api: Fabric API 0.91.0 1.20.1
			fabric-api-base: Fabric API Base 0.4.30 7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35 4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12 215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10 92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0 92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40 b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1 97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33 f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12 b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50 df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63 df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10 57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4 a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18 aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3 d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53 8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22 b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1 e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62 df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39 ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27 b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11 d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36 fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34 df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21 b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0 96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44 9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8 d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49 b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2 709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1 9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10 eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50 df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2 4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1 201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20 b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2 4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0 39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0 39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45 df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36 92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27 b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48 df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7 b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7 29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9 132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7 b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29 b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12 b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3 c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0 6c31357e77
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.1
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		geckolib: GeckoLib 4 4.4
			com_eliotlash_mclib_mclib: mclib 20
		horsestatsvanilla: Horse Stats Vanilla 4.3.0
			libgui: LibGui 8.0.0 1.20
				jankson: Jankson 5.0.1 j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		immediatelyfast: ImmediatelyFast 1.2.8 1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		indium: Indium 1.0.27 mc1.20.1
		invmove: InvMove 0.8.4
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2 1.20.1
			pride: Pride Lib 1.2.0 1.19.4
		lazydfu: LazyDFU 0.1.3
		leaky: leaky Mod 1.20.1-1.6
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.12.1 mc1.20.1
		modmenu: Mod Menu 7.2.2
		nyfsspiders: Nyf's Spiders 2.1.1
		recipeessentials: recipeessentials Mod 1.20.1-3.2
		resourcefulconfig: Resourcefulconfig 2.1.2
		sodium: Sodium 0.5.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.2
		starlight: Starlight 1.1.2 fabric.dbc156f
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1 1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
	Loaded Shaderpack: BSL_v8.2.07.1.zip
		Profile: Custom ( 14 options changed by user)
	Launched Version: fabric-loader-0.15.6-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r539416.zip, minecraft:supporteatinganimation, continuity:glass_pane_culling_fix, fabric, continuity:default
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['kollide'/182, l='ServerLevel[Astalgion]', x=967.19, y=65.00, z=131.75]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable`

**Comment by Nopotato** [comment]
I also have this issue, and I can't update to 1.21.1 because I'm playing with a modpack where it is not feasable to update. 1.20.1 is the most stable and most supported version for a lot of mods on fabric at this time, it would be super lovely if a fix for 1.20.1 would be possible, but I understand if not.
